# Generated by Django 5.1.7 on 2025-03-30 08:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hostel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Hostel Name')),
                ('location', models.CharField(max_length=50, verbose_name='Location')),
                ('room_type', models.CharField(choices=[('AC', 'AC'), ('NON-AC', 'NON-AC')], max_length=20, verbose_name='Room Type')),
                ('food_type', models.CharField(choices=[('Veg', 'Veg'), ('Non-veg', 'Non-Veg')], max_length=20, verbose_name='Food Type')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=10, verbose_name='Gender')),
                ('person_per_room', models.IntegerField()),
                ('no_of_rooms', models.IntegerField()),
                ('total_capacity', models.IntegerField(editable=False)),
                ('room_description', models.CharField(max_length=100)),
                ('amount', models.IntegerField()),
                ('image', models.ImageField(upload_to='rooms/')),
                ('enable', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='RoomBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('otp_pending', 'OTP Pending'), ('payment_pending', 'Payment Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('payment_verified', 'Payment Verified by Admin')], default='otp_pending', max_length=20)),
                ('booked_at', models.DateTimeField(auto_now_add=True)),
                ('otp_verified_at', models.DateTimeField(blank=True, null=True)),
                ('payment_completed_at', models.DateTimeField(blank=True, null=True)),
                ('payment_link', models.URLField(blank=True, max_length=255, null=True)),
                ('payment_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('otp_code', models.CharField(blank=True, max_length=10, null=True)),
                ('otp_expiry', models.DateTimeField(blank=True, null=True)),
                ('payment_expiry', models.DateTimeField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True, null=True)),
                ('hostel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostel.hostel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'hostel')},
            },
        ),
    ]
