# Generated by Django 5.1.7 on 2025-03-31 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0002_roomstats_roombooking_verified_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roombooking',
            name='is_internal_booking',
            field=models.BooleanField(default=False),
        ),
    ]
