# Generated by Django 5.1.7 on 2025-03-31 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0003_roombooking_is_internal_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roombooking',
            name='is_internal_booking',
        ),
    ]
