# Generated by Django 5.1.7 on 2025-03-31 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0004_remove_roombooking_is_internal_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='roombooking',
            name='is_internal_booking',
            field=models.BooleanField(default=False),
        ),
    ]
