# Generated by Django 5.1.7 on 2025-04-04 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0005_roombooking_is_internal_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentManagement',
            fields=[
            ],
            options={
                'verbose_name': 'Payment Management',
                'verbose_name_plural': 'Payment Management',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('hostel.roombooking',),
        ),
        migrations.AddField(
            model_name='hostel',
            name='first_year_fee',
            field=models.IntegerField(default=15000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hostel',
            name='fourth_year_fee',
            field=models.IntegerField(default=15000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hostel',
            name='second_year_fee',
            field=models.IntegerField(default=15000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hostel',
            name='third_year_fee',
            field=models.IntegerField(default=15000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='roombooking',
            name='status',
            field=models.CharField(choices=[('otp_pending', 'OTP Pending'), ('payment_pending', 'Payment Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('payment_not_done', 'Payment Not Done')], default='otp_pending', max_length=20),
        ),
    ]
