# Generated by Django 5.0.2 on 2025-04-01 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hostel", "0005_roombooking_is_internal_booking"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentManagement",
            fields=[],
            options={
                "verbose_name": "Payment Management",
                "verbose_name_plural": "Payment Management",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("hostel.roombooking",),
        ),
        migrations.AlterField(
            model_name="roombooking",
            name="status",
            field=models.CharField(
                choices=[
                    ("otp_pending", "OTP Pending"),
                    ("payment_pending", "Payment Pending"),
                    ("confirmed", "Confirmed"),
                    ("cancelled", "Cancelled"),
                    ("payment_not_done", "Payment Not Done"),
                ],
                default="otp_pending",
                max_length=20,
            ),
        ),
    ]
