# Generated by Django 5.1.7 on 2025-04-04 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0007_hostel_bathroom_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hostel',
            name='amount',
        ),
    ]
