# Generated by Django 5.2 on 2025-04-10 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hostel", "0006_paymentmanagement_alter_roombooking_status"),
        ("hostel", "0008_remove_hostel_amount"),
    ]

    operations = []
