# Generated by Django 5.1.7 on 2025-04-11 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0008_remove_hostel_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostel',
            name='allow_bookings',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='hostel',
            name='image',
            field=models.ImageField(blank=True, default=None, upload_to='rooms/'),
        ),
    ]
