# Generated by Django 5.2 on 2025-04-11 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hostel", "0009_hostel_allow_bookings_alter_hostel_image"),
        ("hostel", "0009_merge_20250410_1614"),
    ]

    operations = []
