# Generated by Django 5.1.7 on 2025-04-11 11:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0010_merge_20250411_1021'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Penalty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('otp_pending', 'OTP Pending'), ('payment_pending', 'Payment Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('payment_not_done', 'Payment Not Done')], default='otp_pending', max_length=20)),
                ('is_internal_booking', models.BooleanField(default=False)),
                ('booked_at', models.DateTimeField(auto_now_add=True)),
                ('otp_verified_at', models.DateTimeField(blank=True, null=True)),
                ('payment_completed_at', models.DateTimeField(blank=True, null=True)),
                ('payment_link', models.URLField(blank=True, max_length=255, null=True)),
                ('payment_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('otp_code', models.CharField(blank=True, max_length=10, null=True)),
                ('otp_expiry', models.DateTimeField(blank=True, null=True)),
                ('payment_expiry', models.DateTimeField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True, null=True)),
                ('hostel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostel.hostel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
