# Generated by Django 5.1.7 on 2025-04-11 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0011_penalty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hostel',
            name='first_year_fee',
        ),
        migrations.RemoveField(
            model_name='hostel',
            name='fourth_year_fee',
        ),
        migrations.RemoveField(
            model_name='hostel',
            name='second_year_fee',
        ),
        migrations.RemoveField(
            model_name='hostel',
            name='third_year_fee',
        ),
        migrations.AddField(
            model_name='hostel',
            name='first_year_fee_govt',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hostel',
            name='first_year_fee_mgmt',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hostel',
            name='fourth_year_fee_govt',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hostel',
            name='fourth_year_fee_mgmt',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hostel',
            name='second_year_fee_govt',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hostel',
            name='second_year_fee_mgmt',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hostel',
            name='third_year_fee_govt',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hostel',
            name='third_year_fee_mgmt',
            field=models.IntegerField(default=0),
        ),
    ]
