# Generated by Django 5.1.7 on 2025-04-11 16:41

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0012_remove_hostel_first_year_fee_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='roombooking',
            unique_together={('user', 'hostel', 'status')},
        ),
    ]
