# Generated by Django 5.1.7 on 2025-04-11 16:46

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0013_alter_roombooking_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='roombooking',
            unique_together={('user', 'hostel', 'status', 'booked_at')},
        ),
    ]
