# Generated by Django 5.1.7 on 2025-04-15 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0014_alter_roombooking_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hostel',
            old_name='first_year_fee_govt',
            new_name='first_year_fee_govt_non_veg',
        ),
        migrations.RenameField(
            model_name='hostel',
            old_name='first_year_fee_mgmt',
            new_name='first_year_fee_govt_veg',
        ),
        migrations.RenameField(
            model_name='hostel',
            old_name='fourth_year_fee_govt',
            new_name='first_year_fee_mgmt_non_veg',
        ),
        migrations.RenameField(
            model_name='hostel',
            old_name='fourth_year_fee_mgmt',
            new_name='first_year_fee_mgmt_veg',
        ),
        migrations.RenameField(
            model_name='hostel',
            old_name='second_year_fee_govt',
            new_name='fourth_year_fee_govt_non_veg',
        ),
        migrations.RenameField(
            model_name='hostel',
            old_name='second_year_fee_mgmt',
            new_name='fourth_year_fee_govt_veg',
        ),
        migrations.RenameField(
            model_name='hostel',
            old_name='third_year_fee_govt',
            new_name='fourth_year_fee_mgmt_non_veg',
        ),
        migrations.RenameField(
            model_name='hostel',
            old_name='third_year_fee_mgmt',
            new_name='fourth_year_fee_mgmt_veg',
        ),
        migrations.RemoveField(
            model_name='hostel',
            name='food_type',
        ),
        migrations.AddField(
            model_name='hostel',
            name='is_non_veg',
            field=models.BooleanField(default=False, verbose_name='Non-Veg Available'),
        ),
        migrations.AddField(
            model_name='hostel',
            name='is_veg',
            field=models.BooleanField(default=True, verbose_name='Veg Available'),
        ),
        migrations.AddField(
            model_name='hostel',
            name='second_year_fee_govt_non_veg',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hostel',
            name='second_year_fee_govt_veg',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hostel',
            name='second_year_fee_mgmt_non_veg',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hostel',
            name='second_year_fee_mgmt_veg',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hostel',
            name='third_year_fee_govt_non_veg',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hostel',
            name='third_year_fee_govt_veg',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hostel',
            name='third_year_fee_mgmt_non_veg',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hostel',
            name='third_year_fee_mgmt_veg',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='roombooking',
            name='food_type',
            field=models.CharField(choices=[('Veg', 'Veg'), ('Non-veg', 'Non-Veg')], default=False, max_length=20, verbose_name='Food Type'),
        ),
    ]
