# Generated by Django 5.1.7 on 2025-04-15 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0015_rename_first_year_fee_govt_hostel_first_year_fee_govt_non_veg_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roombooking',
            name='food_type',
            field=models.CharField(choices=[('Veg', 'Veg'), ('Non-veg', 'Non-Veg')], max_length=20, null=True, verbose_name='Food Type'),
        ),
    ]
