# Generated by Django 5.1.7 on 2025-04-16 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0016_alter_roombooking_food_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roombooking',
            name='food_type',
            field=models.CharField(choices=[('Veg', 'Veg'), ('Non_veg', 'Non-Veg')], max_length=20, null=True, verbose_name='Food Type'),
        ),
    ]
