# Generated by Django 5.1.7 on 2025-04-16 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0018_alter_penalty_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roombooking',
            name='status',
            field=models.CharField(choices=[('otp_pending', 'OTP Pending'), ('payment_pending', 'Payment Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('payment_not_done', 'Payment Not Done'), ('vacated', 'Vacated'), ('course_completed', 'Course Completed')], default='otp_pending', max_length=20),
        ),
    ]
