# Generated by Django 5.1.7 on 2025-04-16 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0019_alter_roombooking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='roombooking',
            name='is_payment_link_sent',
            field=models.BooleanField(default=False),
        ),
    ]
