# Generated by Django 5.1.7 on 2025-07-25 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0021_longdistanceroutes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='longdistanceroutes',
            name='Bus Route Name',
        ),
        migrations.RemoveField(
            model_name='longdistanceroutes',
            name='Bus Route No.',
        ),
        migrations.AddField(
            model_name='longdistanceroutes',
            name='bus_route_name',
            field=models.CharField(default=1, max_length=255, verbose_name='Bus Route Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='longdistanceroutes',
            name='bus_route_no',
            field=models.CharField(default=1, max_length=10, verbose_name='Bus Route No.'),
            preserve_default=False,
        ),
    ]
