# Generated by Django 5.1.7 on 2025-07-25 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0022_remove_longdistanceroutes_bus_route_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostel',
            name='special_fees_transport',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
