# Generated by Django 5.1.7 on 2025-03-30 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='year',
            field=models.IntegerField(default=0, verbose_name='Year'),
        ),
    ]
