# Generated by Django 5.1.7 on 2025-04-10 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_user_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tution_fee',
            field=models.BooleanField(default=False),
        ),
    ]
