# Generated by Django 5.1.7 on 2025-04-11 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_blockedstudents_alter_user_tution_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='student_type',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='Mgmt', max_length=10),
        ),
    ]
