# Generated by Django 5.1.7 on 2025-04-16 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_alter_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='degree_type',
            field=models.CharField(choices=[('UG', 'UG'), ('PG', 'PG')], default='UG', max_length=10),
        ),
    ]
