# Generated by Django 5.1.7 on 2025-07-25 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_user_degree_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_long_distance_student',
            field=models.BooleanField(default=False),
        ),
    ]
